# Generated by Django 2.2.16 on 2021-11-25 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20211125_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user',
            new_name='author',
        ),
    ]
