# Generated by Django 2.2.16 on 2021-11-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20211125_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='user',
        ),
    ]
